name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to Harbor
        run: |
          podman login harbor.towelie.dev -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker image
        run: |
          podman build -t harbor.towelie.dev/library/app-darts:1.0.0 .

      - name: Push Docker image to Harbor
        run: |
          podman push harbor.towelie.dev/library/app-darts:1.0.0

